services:
  app:
    image: helhamaky/twerlo-app:latest
    ports:
      - "8000:8000"  # Backend API
      - "3000:3000"  # Frontend
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped 